// Warning: this file is generated by wrapper.py.

#pragma once

#include "animation.h"

#include "lua++.h"
#include "tools/string.h"

class SkeletonBone_Wrapper {
	static int NewSkeletonBone(lua_State* L) {
		return Lua::newObject<SkeletonBone>(L);
	}

	static int ToString(lua_State* L) {
		SkeletonBone* _p = Lua::callerPtr<SkeletonBone>(L);

		lua_pushstring(L, String::Format("SkeletonBone@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<SkeletonBone>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewSkeletonBone", NewSkeletonBone });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<SkeletonBone> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<SkeletonBone>(L, metalib, nullptr);
	}
};

class SkeletonNode_Wrapper {
	static int NewSkeletonNode(lua_State* L) {
		return Lua::newObject<SkeletonNode>(L);
	}

	static int ToString(lua_State* L) {
		SkeletonNode* _p = Lua::callerPtr<SkeletonNode>(L);

		lua_pushstring(L, String::Format("SkeletonNode@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<SkeletonNode>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewSkeletonNode", NewSkeletonNode });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<SkeletonNode> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<SkeletonNode>(L, metalib, nullptr);
	}
};

class Skeleton_Wrapper {
	static int NewSkeleton(lua_State* L) {
		return Lua::newObject<Skeleton>(L);
	}

	static int ToString(lua_State* L) {
		Skeleton* _p = Lua::callerPtr<Skeleton>(L);

		lua_pushstring(L, String::Format("Skeleton@0x%p", _p).c_str());
		return 1;
	}

	// bool AddBone(const SkeletonBone& bone)
	static int AddBone(lua_State* L) {
		Skeleton* _p = Lua::callerPtr<Skeleton>(L);
		SkeletonBone bone = Lua::get<SkeletonBone>(L, 2);
		
		return Lua::push(L, _p->AddBone(bone));
	}

	// void SetBoneToRootMatrix(uint index, const Matrix4& value)
	static int SetBoneToRootMatrix(lua_State* L) {
		Skeleton* _p = Lua::callerPtr<Skeleton>(L);
		Matrix4 value = Lua::get<Matrix4>(L, 3);
		uint index = Lua::get<uint>(L, 2);
		
		_p->SetBoneToRootMatrix(index, value);
		return 0;
	}

	// int GetBoneIndex(const std::string& name)
	static int GetBoneIndex(lua_State* L) {
		Skeleton* _p = Lua::callerPtr<Skeleton>(L);
		std::string name = Lua::get<std::string>(L, 2);
		
		return Lua::push(L, _p->GetBoneIndex(name));
	}

	// int GetBoneCount()
	static int GetBoneCount(lua_State* L) {
		Skeleton* _p = Lua::callerPtr<Skeleton>(L);
		return Lua::push(L, _p->GetBoneCount());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Skeleton>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewSkeleton", NewSkeleton });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Skeleton> },
			{ "__tostring", ToString }, 
			{ "AddBone", AddBone },
			{ "SetBoneToRootMatrix", SetBoneToRootMatrix },
			{ "GetBoneIndex", GetBoneIndex },
			{ "GetBoneCount", GetBoneCount },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Skeleton>(L, metalib, TypeID<Object>::string());
	}
};

class AnimationClip_Wrapper {
	static int NewAnimationClip(lua_State* L) {
		return Lua::newObject<AnimationClip>(L);
	}

	static int ToString(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);

		lua_pushstring(L, String::Format("AnimationClip@0x%p", _p).c_str());
		return 1;
	}

	// void SetWrapMode(AnimationWrapMode value)
	static int SetWrapMode(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		AnimationWrapMode value = Lua::get<AnimationWrapMode>(L, 2);
		
		_p->SetWrapMode(value);
		return 0;
	}

	// AnimationWrapMode GetWrapMode()
	static int GetWrapMode(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		return Lua::push(L, _p->GetWrapMode());
	}

	// void SetTicksPerSecond(float value)
	static int SetTicksPerSecond(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		float value = Lua::get<float>(L, 2);
		
		_p->SetTicksPerSecond(value);
		return 0;
	}

	// float GetTicksPerSecond()
	static int GetTicksPerSecond(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		return Lua::push(L, _p->GetTicksPerSecond());
	}

	// void SetDuration(float value)
	static int SetDuration(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		float value = Lua::get<float>(L, 2);
		
		_p->SetDuration(value);
		return 0;
	}

	// float GetDuration()
	static int GetDuration(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		return Lua::push(L, _p->GetDuration());
	}

	// bool Sample(float time)
	static int Sample(lua_State* L) {
		AnimationClip* _p = Lua::callerPtr<AnimationClip>(L);
		float time = Lua::get<float>(L, 2);
		
		return Lua::push(L, _p->Sample(time));
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<AnimationClip>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimationClip", NewAnimationClip });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<AnimationClip> },
			{ "__tostring", ToString }, 
			{ "SetWrapMode", SetWrapMode },
			{ "GetWrapMode", GetWrapMode },
			{ "SetTicksPerSecond", SetTicksPerSecond },
			{ "GetTicksPerSecond", GetTicksPerSecond },
			{ "SetDuration", SetDuration },
			{ "GetDuration", GetDuration },
			{ "Sample", Sample },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<AnimationClip>(L, metalib, TypeID<Object>::string());
	}
};

class AnimationState_Wrapper {
	static int NewAnimationState(lua_State* L) {
		return Lua::newObject<AnimationState>(L);
	}

	static int ToString(lua_State* L) {
		AnimationState* _p = Lua::callerPtr<AnimationState>(L);

		lua_pushstring(L, String::Format("AnimationState@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<AnimationState>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimationState", NewAnimationState });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<AnimationState> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<AnimationState>(L, metalib, TypeID<Object>::string());
	}
};

class AnimationKeys_Wrapper {
	static int NewAnimationKeys(lua_State* L) {
		return Lua::newObject<AnimationKeys>(L);
	}

	static int ToString(lua_State* L) {
		AnimationKeys* _p = Lua::callerPtr<AnimationKeys>(L);

		lua_pushstring(L, String::Format("AnimationKeys@0x%p", _p).c_str());
		return 1;
	}

	// void AddFloat(float time, int id, float value)
	static int AddFloat(lua_State* L) {
		AnimationKeys* _p = Lua::callerPtr<AnimationKeys>(L);
		float value = Lua::get<float>(L, 4);
		int id = Lua::get<int>(L, 3);
		float time = Lua::get<float>(L, 2);
		
		_p->AddFloat(time, id, value);
		return 0;
	}

	// void AddVector3(float time, int id, const Vector3& value)
	static int AddVector3(lua_State* L) {
		AnimationKeys* _p = Lua::callerPtr<AnimationKeys>(L);
		Vector3 value = Lua::get<Vector3>(L, 4);
		int id = Lua::get<int>(L, 3);
		float time = Lua::get<float>(L, 2);
		
		_p->AddVector3(time, id, value);
		return 0;
	}

	// void AddQuaternion(float time, int id, const Quaternion& value)
	static int AddQuaternion(lua_State* L) {
		AnimationKeys* _p = Lua::callerPtr<AnimationKeys>(L);
		Quaternion value = Lua::get<Quaternion>(L, 4);
		int id = Lua::get<int>(L, 3);
		float time = Lua::get<float>(L, 2);
		
		_p->AddQuaternion(time, id, value);
		return 0;
	}

	// void Remove(float time, int id)
	static int Remove(lua_State* L) {
		AnimationKeys* _p = Lua::callerPtr<AnimationKeys>(L);
		int id = Lua::get<int>(L, 3);
		float time = Lua::get<float>(L, 2);
		
		_p->Remove(time, id);
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<AnimationKeys>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimationKeys", NewAnimationKeys });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<AnimationKeys> },
			{ "__tostring", ToString }, 
			{ "AddFloat", AddFloat },
			{ "AddVector3", AddVector3 },
			{ "AddQuaternion", AddQuaternion },
			{ "Remove", Remove },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<AnimationKeys>(L, metalib, TypeID<Object>::string());
	}
};

class AnimationFrame_Wrapper {
	static int NewAnimationFrame(lua_State* L) {
		return Lua::newObject<AnimationFrame>(L);
	}

	static int ToString(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);

		lua_pushstring(L, String::Format("AnimationFrame@0x%p", _p).c_str());
		return 1;
	}

	// void SetTime(float value)
	static int SetTime(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		float value = Lua::get<float>(L, 2);
		
		_p->SetTime(value);
		return 0;
	}

	// float GetTime()
	static int GetTime(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		return Lua::push(L, _p->GetTime());
	}

	// void SetFloat(int id, float value)
	static int SetFloat(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		float value = Lua::get<float>(L, 3);
		int id = Lua::get<int>(L, 2);
		
		_p->SetFloat(id, value);
		return 0;
	}

	// void SetVector3(int id, const Vector3& value)
	static int SetVector3(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		Vector3 value = Lua::get<Vector3>(L, 3);
		int id = Lua::get<int>(L, 2);
		
		_p->SetVector3(id, value);
		return 0;
	}

	// void SetQuaternion(int id, const Quaternion& value)
	static int SetQuaternion(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		Quaternion value = Lua::get<Quaternion>(L, 3);
		int id = Lua::get<int>(L, 2);
		
		_p->SetQuaternion(id, value);
		return 0;
	}

	// float GetFloat(int id)
	static int GetFloat(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		int id = Lua::get<int>(L, 2);
		
		return Lua::push(L, _p->GetFloat(id));
	}

	// Vector3 GetVector3(int id)
	static int GetVector3(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		int id = Lua::get<int>(L, 2);
		
		return Lua::push(L, _p->GetVector3(id));
	}

	// Quaternion GetQuaternion(int id)
	static int GetQuaternion(lua_State* L) {
		AnimationFrame* _p = Lua::callerPtr<AnimationFrame>(L);
		int id = Lua::get<int>(L, 2);
		
		return Lua::push(L, _p->GetQuaternion(id));
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<AnimationFrame>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimationFrame", NewAnimationFrame });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<AnimationFrame> },
			{ "__tostring", ToString }, 
			{ "SetTime", SetTime },
			{ "GetTime", GetTime },
			{ "SetFloat", SetFloat },
			{ "SetVector3", SetVector3 },
			{ "SetQuaternion", SetQuaternion },
			{ "GetFloat", GetFloat },
			{ "GetVector3", GetVector3 },
			{ "GetQuaternion", GetQuaternion },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<AnimationFrame>(L, metalib, TypeID<Object>::string());
	}
};

class AnimationCurve_Wrapper {
	static int NewAnimationCurve(lua_State* L) {
		return Lua::newObject<AnimationCurve>(L);
	}

	static int ToString(lua_State* L) {
		AnimationCurve* _p = Lua::callerPtr<AnimationCurve>(L);

		lua_pushstring(L, String::Format("AnimationCurve@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<AnimationCurve>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimationCurve", NewAnimationCurve });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<AnimationCurve> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<AnimationCurve>(L, metalib, TypeID<Object>::string());
	}
};

class Animation_Wrapper {
	static int NewAnimation(lua_State* L) {
		return Lua::newObject<Animation>(L);
	}

	static int ToString(lua_State* L) {
		Animation* _p = Lua::callerPtr<Animation>(L);

		lua_pushstring(L, String::Format("Animation@0x%p", _p).c_str());
		return 1;
	}

	// void SetRootTransform(const Matrix4& value)
	static int SetRootTransform(lua_State* L) {
		Animation* _p = Lua::callerPtr<Animation>(L);
		Matrix4 value = Lua::get<Matrix4>(L, 2);
		
		_p->SetRootTransform(value);
		return 0;
	}

	// Matrix4 GetRootTransform()
	static int GetRootTransform(lua_State* L) {
		Animation* _p = Lua::callerPtr<Animation>(L);
		return Lua::push(L, _p->GetRootTransform());
	}

	// void SetWrapMode(AnimationWrapMode value)
	static int SetWrapMode(lua_State* L) {
		Animation* _p = Lua::callerPtr<Animation>(L);
		AnimationWrapMode value = Lua::get<AnimationWrapMode>(L, 2);
		
		_p->SetWrapMode(value);
		return 0;
	}

	// bool Play(const std::string& name)
	static int Play(lua_State* L) {
		Animation* _p = Lua::callerPtr<Animation>(L);
		std::string name = Lua::get<std::string>(L, 2);
		
		return Lua::push(L, _p->Play(name));
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Animation>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewAnimation", NewAnimation });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Animation> },
			{ "__tostring", ToString }, 
			{ "SetRootTransform", SetRootTransform },
			{ "GetRootTransform", GetRootTransform },
			{ "SetWrapMode", SetWrapMode },
			{ "Play", Play },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Animation>(L, metalib, TypeID<Component>::string());
	}
};
