// Warning: this file is generated by wrapper.py.

#pragma once

#include "../luax.h"
#include "camera.h"

class Camera_Wrapper {
	static int SetDepth(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		int value = Lua::get<int>(L, -1);
		_p->SetDepth(value);
		return 0;
	}

	static int GetDepth(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetDepth());
	}

	static int GetPerspective(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetPerspective());
	}

	static int SetPerspective(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		bool value = Lua::get<bool>(L, -1);
		_p->SetPerspective(value);
		return 0;
	}

	static int GetOrthographicSize(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetOrthographicSize());
	}

	static int SetOrthographicSize(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		float value = Lua::get<float>(L, -1);
		_p->SetOrthographicSize(value);
		return 0;
	}

	static int SetClearType(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		ClearType value = Lua::get<ClearType>(L, -1);
		_p->SetClearType(value);
		return 0;
	}

	static int GetClearType(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetClearType());
	}

	static int SetRenderPath(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		RenderPath value = Lua::get<RenderPath>(L, -1);
		_p->SetRenderPath(value);
		return 0;
	}

	static int GetRenderPath(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetRenderPath());
	}

	static int SetDepthTextureMode(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		DepthTextureMode value = Lua::get<DepthTextureMode>(L, -1);
		_p->SetDepthTextureMode(value);
		return 0;
	}

	static int GetDepthTextureMode(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetDepthTextureMode());
	}

	static int SetClearColor(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		Color value = Lua::get<Color>(L, -1);
		_p->SetClearColor(value);
		return 0;
	}

	static int GetClearColor(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetClearColor());
	}

	static int SetTargetTexture(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		RenderTexture value = Lua::get<RenderTexture>(L, -1);
		_p->SetTargetTexture(value);
		return 0;
	}

	static int GetTargetTexture(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetTargetTexture());
	}

	static int SetAspect(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		float value = Lua::get<float>(L, -1);
		_p->SetAspect(value);
		return 0;
	}

	static int GetAspect(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetAspect());
	}

	static int SetNearClipPlane(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		float value = Lua::get<float>(L, -1);
		_p->SetNearClipPlane(value);
		return 0;
	}

	static int GetNearClipPlane(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetNearClipPlane());
	}

	static int SetFarClipPlane(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		float value = Lua::get<float>(L, -1);
		_p->SetFarClipPlane(value);
		return 0;
	}

	static int GetFarClipPlane(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetFarClipPlane());
	}

	static int SetFieldOfView(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		float value = Lua::get<float>(L, -1);
		_p->SetFieldOfView(value);
		return 0;
	}

	static int GetFieldOfView(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->GetFieldOfView());
	}

	static int SetRect(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		Rect value = Lua::get<Rect>(L, -1);
		_p->SetRect(value);
		return 0;
	}

	static int GetVisibleGameObjects(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		std::vector<GameObject> gameObjects = Lua::getList<GameObject>(L, -1);
		_p->GetVisibleGameObjects(gameObjects);
		return 0;
	}

	static int WorldToScreenPoint(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		glm::vec3 position = Lua::get<glm::vec3>(L, -1);
		return Lua::push(L, _p->WorldToScreenPoint(position));
	}

	static int ScreenToWorldPoint(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 1);
		glm::vec3 position = Lua::get<glm::vec3>(L, -1);
		return Lua::push(L, _p->ScreenToWorldPoint(position));
	}

	static int Capture(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		return Lua::push(L, _p->Capture());
	}

	static int Render(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		_p->Render();
		return 0;
	}

	static int OnBeforeWorldDestroyed(lua_State* L) {
		Camera& _p = *Lua::callerSharedPtr<Camera>(L, 0);
		_p->OnBeforeWorldDestroyed();
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Camera>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteSharedPtr<Camera> },
			{ "SetDepth", SetDepth },
			{ "GetDepth", GetDepth },
			{ "GetPerspective", GetPerspective },
			{ "SetPerspective", SetPerspective },
			{ "GetOrthographicSize", GetOrthographicSize },
			{ "SetOrthographicSize", SetOrthographicSize },
			{ "SetClearType", SetClearType },
			{ "GetClearType", GetClearType },
			{ "SetRenderPath", SetRenderPath },
			{ "GetRenderPath", GetRenderPath },
			{ "SetDepthTextureMode", SetDepthTextureMode },
			{ "GetDepthTextureMode", GetDepthTextureMode },
			{ "SetClearColor", SetClearColor },
			{ "GetClearColor", GetClearColor },
			{ "SetTargetTexture", SetTargetTexture },
			{ "GetTargetTexture", GetTargetTexture },
			{ "SetAspect", SetAspect },
			{ "GetAspect", GetAspect },
			{ "SetNearClipPlane", SetNearClipPlane },
			{ "GetNearClipPlane", GetNearClipPlane },
			{ "SetFarClipPlane", SetFarClipPlane },
			{ "GetFarClipPlane", GetFarClipPlane },
			{ "SetFieldOfView", SetFieldOfView },
			{ "GetFieldOfView", GetFieldOfView },
			{ "SetRect", SetRect },
			{ "GetVisibleGameObjects", GetVisibleGameObjects },
			{ "WorldToScreenPoint", WorldToScreenPoint },
			{ "ScreenToWorldPoint", ScreenToWorldPoint },
			{ "Capture", Capture },
			{ "Render", Render },
			{ "OnBeforeWorldDestroyed", OnBeforeWorldDestroyed },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Camera>(L, metalib, Lua::metatableName<Component>());
	}
};
