// Warning: this file is generated by wrapper.py.

#pragma once

#include "lua++.h"
#include "environment.h"

class Environment_Wrapper {
	static int EnvironmentInstance(lua_State* L) {
		return Lua::reference<Environment>(L);
	}

	static int SetSkybox(lua_State* L) {
		Environment* _p = Environment::instance();
		Material value = Lua::get<Material>(L, 2);
		_p->SetSkybox(value);
		return 0;
	}

	static int GetSkybox(lua_State* L) {
		Environment* _p = Environment::instance();
		return Lua::push(L, _p->GetSkybox());
	}

	static int SetAmbientColor(lua_State* L) {
		Environment* _p = Environment::instance();
		Color value = Lua::get<Color>(L, 2);
		_p->SetAmbientColor(value);
		return 0;
	}

	static int GetAmbientColor(lua_State* L) {
		Environment* _p = Environment::instance();
		return Lua::push(L, _p->GetAmbientColor());
	}

	static int SetFogColor(lua_State* L) {
		Environment* _p = Environment::instance();
		Color value = Lua::get<Color>(L, 2);
		_p->SetFogColor(value);
		return 0;
	}

	static int GetFogColor(lua_State* L) {
		Environment* _p = Environment::instance();
		return Lua::push(L, _p->GetFogColor());
	}

	static int SetFogDensity(lua_State* L) {
		Environment* _p = Environment::instance();
		float value = Lua::get<float>(L, 2);
		_p->SetFogDensity(value);
		return 0;
	}

	static int GetFogDensity(lua_State* L) {
		Environment* _p = Environment::instance();
		return Lua::push(L, _p->GetFogDensity());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Environment>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		regs.push_back(luaL_Reg { "EnvironmentInstance", EnvironmentInstance });

		luaL_Reg metalib[] = {
			{ "SetSkybox", SetSkybox },
			{ "GetSkybox", GetSkybox },
			{ "SetAmbientColor", SetAmbientColor },
			{ "GetAmbientColor", GetAmbientColor },
			{ "SetFogColor", SetFogColor },
			{ "GetFogColor", GetFogColor },
			{ "SetFogDensity", SetFogDensity },
			{ "GetFogDensity", GetFogDensity },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Environment>(L, metalib, nullptr);
	}
};
