// Warning: this file is generated by wrapper.py.

#pragma once

#include "font.h"

#include "lua++.h"
#include "tools/string.h"

class CharacterInfo_Wrapper {
	static int NewCharacterInfo(lua_State* L) {
		return Lua::newObject<CharacterInfo>(L);
	}

	static int ToString(lua_State* L) {
		CharacterInfo* _p = Lua::callerPtr<CharacterInfo>(L);

		lua_pushstring(L, String::Format("CharacterInfo@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<CharacterInfo>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewCharacterInfo", NewCharacterInfo });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<CharacterInfo> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<CharacterInfo>(L, metalib, nullptr);
	}
};

class Font_Wrapper {
	static int NewFont(lua_State* L) {
		return Lua::fromShared(L, ::NewFont());
	}

	static int ToString(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);

		lua_pushstring(L, String::Format("Font@0x%p", _p.get()).c_str());
		return 1;
	}

	// bool Load(const std::string& path, int size)
	static int Load(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		int size = Lua::get<int>(L, 3);
		std::string path = Lua::get<std::string>(L, 2);
		
		return Lua::push(L, _p->Load(path, size));
	}

	// bool Require(const std::wstring& str)
	static int Require(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		std::wstring str = Lua::get<std::wstring>(L, 2);
		
		return Lua::push(L, _p->Require(str));
	}

	// uint GetFontSize()
	static int GetFontSize(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		return Lua::push(L, _p->GetFontSize());
	}

	// Texture2D GetTexture()
	static int GetTexture(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		return Lua::push(L, _p->GetTexture());
	}

	// std::string GetFamilyName()
	static int GetFamilyName(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		return Lua::push(L, _p->GetFamilyName());
	}

	// std::string GetStyleName()
	static int GetStyleName(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		return Lua::push(L, _p->GetStyleName());
	}

	// Material GetMaterial()
	static int GetMaterial(lua_State* L) {
		Font& _p = *Lua::callerSharedPtr<Font>(L);
		return Lua::push(L, _p->GetMaterial());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Font>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewFont", NewFont });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteSharedPtr<Font> },
			{ "__tostring", ToString }, 
			{ "Load", Load },
			{ "Require", Require },
			{ "GetFontSize", GetFontSize },
			{ "GetTexture", GetTexture },
			{ "GetFamilyName", GetFamilyName },
			{ "GetStyleName", GetStyleName },
			{ "GetMaterial", GetMaterial },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Font>(L, metalib, TypeID<Object>::string());
	}
};
