// Warning: this file is generated by wrapper.py.

#pragma once

#include "../luax.h"
#include "gameobjectimportedlistener.h"

class GameObjectImportedListener_Wrapper {
	static int NewGameObjectImportedListener(lua_State* L) {
		return Lua::newInterface<GameObjectImportedListenerInternal>(L);
	}

	static int OnGameObjectImported(lua_State* L) {
		GameObjectImportedListener* _p = Lua::callerPtr<GameObjectImportedListener>(L, 2);
		GameObject root = Lua::get<GameObject>(L, -1);
		std::string path = Lua::get<std::string>(L, -2);
		_p->OnGameObjectImported(root, path);
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<GameObjectImportedListener>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		regs.push_back(luaL_Reg { "NewGameObjectImportedListener", NewGameObjectImportedListener });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<GameObjectImportedListener> },
			{ "OnGameObjectImported", OnGameObjectImported },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<GameObjectImportedListener>(L, metalib, nullptr);
	}
};
