// Warning: this file is generated by wrapper.py.

#pragma once

#include "imageeffect.h"

#include "lua++.h"
#include "tools/string.h"

class ImageEffect_Wrapper {
	static int NewImageEffect(lua_State* L) {
		return Lua::newObject<ImageEffect>(L);
	}

	static int ToString(lua_State* L) {
		ImageEffect* _p = Lua::callerPtr<ImageEffect>(L);

		lua_pushstring(L, String::Format("ImageEffect@0x%p", _p).c_str());
		return 1;
	}

	// virtual void OnRenderImage(RenderTexture src, RenderTexture dest, const Rect& normalizedRect)
	static int OnRenderImage(lua_State* L) {
		ImageEffect* _p = Lua::callerPtr<ImageEffect>(L);
		Rect normalizedRect = Lua::get<Rect>(L, 4);
		RenderTexture dest = Lua::get<RenderTexture>(L, 3);
		RenderTexture src = Lua::get<RenderTexture>(L, 2);
		
		_p->OnRenderImage(src, dest, normalizedRect);
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<ImageEffect>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewImageEffect", NewImageEffect });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<ImageEffect> },
			{ "__tostring", ToString }, 
			{ "OnRenderImage", OnRenderImage },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<ImageEffect>(L, metalib, TypeID<Behaviour>::string());
	}
};
