// Warning: this file is generated by wrapper.py.

#pragma once

#include "lua++.h"
#include "material.h"

class Material_Wrapper {
	static int NewMaterial(lua_State* L) {
		return Lua::fromShared(L, ::NewMaterial());
	}

	static int SetName(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string value = Lua::get<std::string>(L, 2);
		_p->SetName(value);
		return 0;
	}

	static int GetName(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		return Lua::push(L, _p->GetName());
	}

	static int Bind(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		uint pass = Lua::get<uint>(L, 2);
		_p->Bind(pass);
		return 0;
	}

	static int Unbind(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		_p->Unbind();
		return 0;
	}

	static int EnablePass(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		uint pass = Lua::get<uint>(L, 2);
		return Lua::push(L, _p->EnablePass(pass));
	}

	static int DisablePass(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		uint pass = Lua::get<uint>(L, 2);
		return Lua::push(L, _p->DisablePass(pass));
	}

	static int IsPassEnabled(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		uint pass = Lua::get<uint>(L, 2);
		return Lua::push(L, _p->IsPassEnabled(pass));
	}

	static int FindPass(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->FindPass(name));
	}

	static int SetPass(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		int pass = Lua::get<int>(L, 2);
		_p->SetPass(pass);
		return 0;
	}

	static int GetPass(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		return Lua::push(L, _p->GetPass());
	}

	static int GetPassCount(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		return Lua::push(L, _p->GetPassCount());
	}

	static int GetPassNativePointer(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		uint pass = Lua::get<uint>(L, 2);
		return Lua::push(L, _p->GetPassNativePointer(pass));
	}

	static int SetShader(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		Shader value = Lua::get<Shader>(L, 2);
		_p->SetShader(value);
		return 0;
	}

	static int GetShader(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		return Lua::push(L, _p->GetShader());
	}

	static int SetRenderQueue(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		int value = Lua::get<int>(L, 2);
		_p->SetRenderQueue(value);
		return 0;
	}

	static int GetRenderQueue(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 0);
		return Lua::push(L, _p->GetRenderQueue());
	}

	static int Define(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		_p->Define(name);
		return 0;
	}

	static int Undefine(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		_p->Undefine(name);
		return 0;
	}

	static int SetInt(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		int value = Lua::get<int>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetInt(name, value);
		return 0;
	}

	static int SetBool(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		bool value = Lua::get<bool>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetBool(name, value);
		return 0;
	}

	static int SetFloat(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		float value = Lua::get<float>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetFloat(name, value);
		return 0;
	}

	static int SetTexture(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		Texture value = Lua::get<Texture>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetTexture(name, value);
		return 0;
	}

	static int SetMatrix4(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		glm::mat4 value = Lua::get<glm::mat4>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetMatrix4(name, value);
		return 0;
	}

	static int SetVector3(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		glm::vec3 value = Lua::get<glm::vec3>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetVector3(name, value);
		return 0;
	}

	static int SetColor(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		Color value = Lua::get<Color>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetColor(name, value);
		return 0;
	}

	static int SetVector4(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		glm::vec4 value = Lua::get<glm::vec4>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetVector4(name, value);
		return 0;
	}

	static int SetVariant(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 2);
		Variant value = Lua::get<Variant>(L, 3);
		std::string name = Lua::get<std::string>(L, 2);
		_p->SetVariant(name, value);
		return 0;
	}

	static int GetInt(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetInt(name));
	}

	static int GetBool(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetBool(name));
	}

	static int GetFloat(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetFloat(name));
	}

	static int GetRangedInt(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetRangedInt(name));
	}

	static int GetRangedFloat(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetRangedFloat(name));
	}

	static int GetTexture(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetTexture(name));
	}

	static int GetMatrix4(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetMatrix4(name));
	}

	static int GetVector3(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetVector3(name));
	}

	static int GetColor(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetColor(name));
	}

	static int GetVector4(lua_State* L) {
		Material& _p = *Lua::callerSharedPtr<Material>(L, 1);
		std::string name = Lua::get<std::string>(L, 2);
		return Lua::push(L, _p->GetVector4(name));
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Material>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		regs.push_back(luaL_Reg { "NewMaterial", NewMaterial });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteSharedPtr<Material> },
			{ "SetName", SetName },
			{ "GetName", GetName },
			{ "Bind", Bind },
			{ "Unbind", Unbind },
			{ "EnablePass", EnablePass },
			{ "DisablePass", DisablePass },
			{ "IsPassEnabled", IsPassEnabled },
			{ "FindPass", FindPass },
			{ "SetPass", SetPass },
			{ "GetPass", GetPass },
			{ "GetPassCount", GetPassCount },
			{ "GetPassNativePointer", GetPassNativePointer },
			{ "SetShader", SetShader },
			{ "GetShader", GetShader },
			{ "SetRenderQueue", SetRenderQueue },
			{ "GetRenderQueue", GetRenderQueue },
			{ "Define", Define },
			{ "Undefine", Undefine },
			{ "SetInt", SetInt },
			{ "SetBool", SetBool },
			{ "SetFloat", SetFloat },
			{ "SetTexture", SetTexture },
			{ "SetMatrix4", SetMatrix4 },
			{ "SetVector3", SetVector3 },
			{ "SetColor", SetColor },
			{ "SetVector4", SetVector4 },
			{ "SetVariant", SetVariant },
			{ "GetInt", GetInt },
			{ "GetBool", GetBool },
			{ "GetFloat", GetFloat },
			{ "GetRangedInt", GetRangedInt },
			{ "GetRangedFloat", GetRangedFloat },
			{ "GetTexture", GetTexture },
			{ "GetMatrix4", GetMatrix4 },
			{ "GetVector3", GetVector3 },
			{ "GetColor", GetColor },
			{ "GetVector4", GetVector4 },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Material>(L, metalib, Lua::metatableName<Object>());
	}
};
