// Warning: this file is generated by wrapper.py.

#pragma once

#include "object.h"

#include "lua++.h"
#include "tools/string.h"

class Object_Wrapper {
	static int ToString(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);

		lua_pushstring(L, String::Format("Object@0x%p", _p.get()).c_str());
		return 1;
	}

	// std::string GetName()
	static int GetName(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);
		return Lua::push(L, _p->GetName());
	}

	// void SetName(const std::string& value)
	static int SetName(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);
		std::string value = Lua::get<std::string>(L, 2);
		
		_p->SetName(value);
		return 0;
	}

	// Object Clone()
	static int Clone(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);
		return Lua::push(L, _p->Clone());
	}

	// ObjectType GetObjectType()
	static int GetObjectType(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);
		return Lua::push(L, _p->GetObjectType());
	}

	// uint GetInstanceID()
	static int GetInstanceID(lua_State* L) {
		Object& _p = *Lua::callerIntrusivePtr<Object>(L);
		return Lua::push(L, _p->GetInstanceID());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Object>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteIntrusivePtr<Object> },
			{ "__tostring", ToString }, 
			{ "GetName", GetName },
			{ "SetName", SetName },
			{ "Clone", Clone },
			{ "GetObjectType", GetObjectType },
			{ "GetInstanceID", GetInstanceID },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Object>(L, metalib, TypeID<PimplIdiom>::string());
	}
};
