// Warning: this file is generated by wrapper.py.

#pragma once

#include "plane.h"

#include "lua++.h"
#include "tools/string.h"

class Plane_Wrapper {
	static int NewPlane(lua_State* L) {
		return Lua::newObject<Plane>(L);
	}

	static int ToString(lua_State* L) {
		Plane* _p = Lua::callerPtr<Plane>(L);

		lua_pushstring(L, String::Format("Plane@0x%p", _p).c_str());
		return 1;
	}

	// float GetDistance()
	static int GetDistance(lua_State* L) {
		Plane* _p = Lua::callerPtr<Plane>(L);
		return Lua::push(L, _p->GetDistance());
	}

	// glm::vec3 GetNormal()
	static int GetNormal(lua_State* L) {
		Plane* _p = Lua::callerPtr<Plane>(L);
		return Lua::push(L, _p->GetNormal());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Plane>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewPlane", NewPlane });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Plane> },
			{ "__tostring", ToString }, 
			{ "GetDistance", GetDistance },
			{ "GetNormal", GetNormal },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Plane>(L, metalib, nullptr);
	}
};
