// Warning: this file is generated by wrapper.py.

#pragma once

#include "../luax.h"
#include "plane.h"

class Plane_Wrapper {
	static int NewPlane(lua_State* L) {
		return Lua::newObject<Plane>(L);
	}

	static int GetDistance(lua_State* L) {
		Plane* _p = Lua::callerPtr<Plane>(L, 0);
		return Lua::push(L, _p->GetDistance());
	}

	static int GetNormal(lua_State* L) {
		Plane* _p = Lua::callerPtr<Plane>(L, 0);
		return Lua::push(L, _p->GetNormal());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Plane>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		regs.push_back(luaL_Reg { "NewPlane", NewPlane });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Plane> },
			{ "GetDistance", GetDistance },
			{ "GetNormal", GetNormal },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Plane>(L, metalib, nullptr);
	}
};
