// Warning: this file is generated by wrapper.py.

#pragma once

#include "projector.h"

#include "lua++.h"
#include "tools/string.h"

class Decal_Wrapper {
	static int NewDecal(lua_State* L) {
		return Lua::newObject<Decal>(L);
	}

	static int ToString(lua_State* L) {
		Decal* _p = Lua::callerPtr<Decal>(L);
		lua_pushstring(L, String::Format("Decal@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Decal>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewDecal", NewDecal });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Decal> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Decal>(L, metalib, nullptr);
	}
};

class Projector_Wrapper {
	static int ToString(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		lua_pushstring(L, String::Format("Projector@0x%p", _p.get()).c_str());
		return 1;
	}

	// bool GetPerspective()
	static int GetPerspective(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetPerspective());
	}

	// void SetPerspective(bool value)
	static int SetPerspective(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		bool value = Lua::get<bool>(L, 2);
		_p->SetPerspective(value);
		return 0;
	}

	// float GetOrthographicSize()
	static int GetOrthographicSize(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetOrthographicSize());
	}

	// void SetOrthographicSize(float value)
	static int SetOrthographicSize(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		float value = Lua::get<float>(L, 2);
		_p->SetOrthographicSize(value);
		return 0;
	}

	// Texture GetTexture()
	static int GetTexture(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetTexture());
	}

	// void SetTexture(Texture value)
	static int SetTexture(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		Texture value = Lua::get<Texture>(L, 2);
		_p->SetTexture(value);
		return 0;
	}

	// void SetDepth(int value)
	static int SetDepth(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		int value = Lua::get<int>(L, 2);
		_p->SetDepth(value);
		return 0;
	}

	// int GetDepth()
	static int GetDepth(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetDepth());
	}

	// void SetAspect(float value)
	static int SetAspect(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		float value = Lua::get<float>(L, 2);
		_p->SetAspect(value);
		return 0;
	}

	// void SetNearClipPlane(float value)
	static int SetNearClipPlane(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		float value = Lua::get<float>(L, 2);
		_p->SetNearClipPlane(value);
		return 0;
	}

	// void SetFarClipPlane(float value)
	static int SetFarClipPlane(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		float value = Lua::get<float>(L, 2);
		_p->SetFarClipPlane(value);
		return 0;
	}

	// void SetFieldOfView(float value)
	static int SetFieldOfView(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		float value = Lua::get<float>(L, 2);
		_p->SetFieldOfView(value);
		return 0;
	}

	// float GetAspect()
	static int GetAspect(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetAspect());
	}

	// float GetNearClipPlane()
	static int GetNearClipPlane(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetNearClipPlane());
	}

	// float GetFarClipPlane()
	static int GetFarClipPlane(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetFarClipPlane());
	}

	// float GetFieldOfView()
	static int GetFieldOfView(lua_State* L) {
		Projector& _p = *Lua::callerSharedPtr<Projector>(L);
		return Lua::push(L, _p->GetFieldOfView());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Projector>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteSharedPtr<Projector> },
			{ "__tostring", ToString }, 
			{ "GetPerspective", GetPerspective },
			{ "SetPerspective", SetPerspective },
			{ "GetOrthographicSize", GetOrthographicSize },
			{ "SetOrthographicSize", SetOrthographicSize },
			{ "GetTexture", GetTexture },
			{ "SetTexture", SetTexture },
			{ "SetDepth", SetDepth },
			{ "GetDepth", GetDepth },
			{ "SetAspect", SetAspect },
			{ "SetNearClipPlane", SetNearClipPlane },
			{ "SetFarClipPlane", SetFarClipPlane },
			{ "SetFieldOfView", SetFieldOfView },
			{ "GetAspect", GetAspect },
			{ "GetNearClipPlane", GetNearClipPlane },
			{ "GetFarClipPlane", GetFarClipPlane },
			{ "GetFieldOfView", GetFieldOfView },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Projector>(L, metalib, TypeID<Component>::string());
	}
};
