// Warning: this file is generated by wrapper.py.

#pragma once

#include "resources.h"

#include "lua++.h"
#include "tools/string.h"

class Resources_Wrapper {
	static int ToString(lua_State* L) {
		Resources* _p = Lua::callerPtr<Resources>(L);

		lua_pushstring(L, String::Format("Resources@0x%p", _p).c_str());
		return 1;
	}

	static int ToStringStatic(lua_State* L) {
		lua_pushstring(L, "static Resources");
		return 1;
	}

	static int ResourcesStatic(lua_State* L) {
		lua_newtable(L);

		luaL_Reg funcs[] = {
			{ "Import", Import },
			{ "GetRootDirectory", GetRootDirectory },
			{ "GetModelDirectory", GetModelDirectory },
			{ "GetShaderDirectory", GetShaderDirectory },
			{ "GetTextureDirectory", GetTextureDirectory },
			{ "GetPrimitiveAttribute", GetPrimitiveAttribute },
			{"__tostring", ToStringStatic },
			{ nullptr, nullptr }
		};

		luaL_setfuncs(L, funcs, 0);

		return 1;
	}
	// static void Import()
	static int Import(lua_State* L) {
		Resources::Import();
		return 0;
	}

	// static std::string GetRootDirectory()
	static int GetRootDirectory(lua_State* L) {
		return Lua::push(L, Resources::GetRootDirectory());
	}

	// static std::string GetModelDirectory()
	static int GetModelDirectory(lua_State* L) {
		return Lua::push(L, Resources::GetModelDirectory());
	}

	// static std::string GetShaderDirectory()
	static int GetShaderDirectory(lua_State* L) {
		return Lua::push(L, Resources::GetShaderDirectory());
	}

	// static std::string GetTextureDirectory()
	static int GetTextureDirectory(lua_State* L) {
		return Lua::push(L, Resources::GetTextureDirectory());
	}

	// static void GetPrimitiveAttribute(MeshAttribute& attribute, PrimitiveType type, float scale)
	static int GetPrimitiveAttribute(lua_State* L) {
		float scale = Lua::get<float>(L, 3);
		PrimitiveType type = Lua::get<PrimitiveType>(L, 2);
		MeshAttribute attribute = Lua::get<MeshAttribute>(L, 1);
		
		Resources::GetPrimitiveAttribute(attribute, type, scale);
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Resources>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		fields.push_back(luaL_Reg{ "Resources", ResourcesStatic });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Resources> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Resources>(L, metalib, nullptr);
	}
};
