// Warning: this file is generated by wrapper.py.

#pragma once

#include "rigidbody.h"

#include "lua++.h"
#include "tools/string.h"

class Rigidbody_Wrapper {
	static int NewRigidbody(lua_State* L) {
		return Lua::fromIntrusive(L, new IRigidbody());
	}

	static int ToString(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);

		lua_pushstring(L, String::Format("Rigidbody@0x%p", _p.get()).c_str());
		return 1;
	}

	// void SetMass(float value)
	static int SetMass(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		float value = Lua::get<float>(L, 2);
		
		_p->SetMass(value);
		return 0;
	}

	// float GetMass()
	static int GetMass(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		return Lua::push(L, _p->GetMass());
	}

	// void SetOccluderEnabled(bool value)
	static int SetOccluderEnabled(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		bool value = Lua::get<bool>(L, 2);
		
		_p->SetOccluderEnabled(value);
		return 0;
	}

	// bool GetOccluderEnabled()
	static int GetOccluderEnabled(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		return Lua::push(L, _p->GetOccluderEnabled());
	}

	// void SetVelocity(const glm::vec3& value)
	static int SetVelocity(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetVelocity(value);
		return 0;
	}

	// glm::vec3 GetVelocity()
	static int GetVelocity(lua_State* L) {
		Rigidbody& _p = *Lua::callerIntrusivePtr<Rigidbody>(L);
		return Lua::push(L, _p->GetVelocity());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Rigidbody>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewRigidbody", NewRigidbody });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteIntrusivePtr<Rigidbody> },
			{ "__tostring", ToString }, 
			{ "SetMass", SetMass },
			{ "GetMass", GetMass },
			{ "SetOccluderEnabled", SetOccluderEnabled },
			{ "GetOccluderEnabled", GetOccluderEnabled },
			{ "SetVelocity", SetVelocity },
			{ "GetVelocity", GetVelocity },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Rigidbody>(L, metalib, TypeID<Component>::string());
	}
};
