// Warning: this file is generated by wrapper.py.

#pragma once

#include "screen.h"

#include "lua++.h"
#include "tools/string.h"

class Screen_Wrapper {
	static int ToString(lua_State* L) {
		Screen* _p = Lua::callerPtr<Screen>(L);

		lua_pushstring(L, String::Format("Screen@0x%p", _p).c_str());
		return 1;
	}

	static int ToStringStatic(lua_State* L) {
		lua_pushstring(L, "static Screen");
		return 1;
	}

	static int ScreenStatic(lua_State* L) {
		lua_newtable(L);

		luaL_Reg funcs[] = {
			{ "GetWidth", GetWidth },
			{ "GetHeight", GetHeight },
			{ "Resize", Resize },
			{"__tostring", ToStringStatic },
			{ nullptr, nullptr }
		};

		luaL_setfuncs(L, funcs, 0);

		return 1;
	}
	// static uint GetWidth()
	static int GetWidth(lua_State* L) {
		return Lua::push(L, Screen::GetWidth());
	}

	// static uint GetHeight()
	static int GetHeight(lua_State* L) {
		return Lua::push(L, Screen::GetHeight());
	}

	// static void Resize(uint width, uint height)
	static int Resize(lua_State* L) {
		uint height = Lua::get<uint>(L, 2);
		uint width = Lua::get<uint>(L, 1);
		
		Screen::Resize(width, height);
		return 0;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Screen>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		fields.push_back(luaL_Reg{ "Screen", ScreenStatic });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<Screen> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Screen>(L, metalib, nullptr);
	}
};
