// Warning: this file is generated by wrapper.py.

#pragma once

#include "statistics.h"

#include "lua++.h"
#include "tools/string.h"

class Statistics_Wrapper {
	static int StatisticsInstance(lua_State* L) {
		return Lua::reference<Statistics>(L);
	}

	static int ToString(lua_State* L) {
		Statistics* _p = Statistics::instance();
		lua_pushstring(L, String::Format("Statistics@0x%p", _p).c_str());
		return 1;
	}

	// void AddTriangles(uint n)
	static int AddTriangles(lua_State* L) {
		Statistics* _p = Statistics::instance();
		uint n = Lua::get<uint>(L, 2);
		_p->AddTriangles(n);
		return 0;
	}

	// void AddDrawcalls(uint n)
	static int AddDrawcalls(lua_State* L) {
		Statistics* _p = Statistics::instance();
		uint n = Lua::get<uint>(L, 2);
		_p->AddDrawcalls(n);
		return 0;
	}

	// uint GetTriangles()
	static int GetTriangles(lua_State* L) {
		Statistics* _p = Statistics::instance();
		return Lua::push(L, _p->GetTriangles());
	}

	// uint GetDrawcalls()
	static int GetDrawcalls(lua_State* L) {
		Statistics* _p = Statistics::instance();
		return Lua::push(L, _p->GetDrawcalls());
	}

	// float GetFrameRate()
	static int GetFrameRate(lua_State* L) {
		Statistics* _p = Statistics::instance();
		return Lua::push(L, _p->GetFrameRate());
	}

	// void SetCullingElapsed(double value)
	static int SetCullingElapsed(lua_State* L) {
		Statistics* _p = Statistics::instance();
		double value = Lua::get<double>(L, 2);
		_p->SetCullingElapsed(value);
		return 0;
	}

	// void SetRenderingElapsed(double value)
	static int SetRenderingElapsed(lua_State* L) {
		Statistics* _p = Statistics::instance();
		double value = Lua::get<double>(L, 2);
		_p->SetRenderingElapsed(value);
		return 0;
	}

	// double GetCullingElapsed()
	static int GetCullingElapsed(lua_State* L) {
		Statistics* _p = Statistics::instance();
		return Lua::push(L, _p->GetCullingElapsed());
	}

	// double GetRenderingElapsed()
	static int GetRenderingElapsed(lua_State* L) {
		Statistics* _p = Statistics::instance();
		return Lua::push(L, _p->GetRenderingElapsed());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Statistics>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& regs) {
		regs.push_back(luaL_Reg { "StatisticsInstance", StatisticsInstance });

		luaL_Reg metalib[] = {
			{ "AddTriangles", AddTriangles },
			{ "AddDrawcalls", AddDrawcalls },
			{ "GetTriangles", GetTriangles },
			{ "GetDrawcalls", GetDrawcalls },
			{ "GetFrameRate", GetFrameRate },
			{ "SetCullingElapsed", SetCullingElapsed },
			{ "SetRenderingElapsed", SetRenderingElapsed },
			{ "GetCullingElapsed", GetCullingElapsed },
			{ "GetRenderingElapsed", GetRenderingElapsed },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Statistics>(L, metalib, nullptr);
	}
};
