// Warning: this file is generated by wrapper.py.

#pragma once

#include "time2.h"

#include "lua++.h"
#include "tools/string.h"

class Time_Wrapper {
	static int TimeInstance(lua_State* L) {
		return Lua::reference<Time>(L);
	}

	static int ToString(lua_State* L) {
		Time* _p = Time::instance();

		lua_pushstring(L, String::Format("Time@0x%p", _p).c_str());
		return 1;
	}

	// float GetTime()
	static int GetTime(lua_State* L) {
		Time* _p = Time::instance();
		return Lua::push(L, _p->GetTime());
	}

	// float GetDeltaTime()
	static int GetDeltaTime(lua_State* L) {
		Time* _p = Time::instance();
		return Lua::push(L, _p->GetDeltaTime());
	}

	// float GetRealTimeSinceStartup()
	static int GetRealTimeSinceStartup(lua_State* L) {
		Time* _p = Time::instance();
		return Lua::push(L, _p->GetRealTimeSinceStartup());
	}

	// uint GetFrameCount()
	static int GetFrameCount(lua_State* L) {
		Time* _p = Time::instance();
		return Lua::push(L, _p->GetFrameCount());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Time>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "TimeInstance", TimeInstance });

		luaL_Reg metalib[] = {
			{ "GetTime", GetTime },
			{ "GetDeltaTime", GetDeltaTime },
			{ "GetRealTimeSinceStartup", GetRealTimeSinceStartup },
			{ "GetFrameCount", GetFrameCount },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Time>(L, metalib, nullptr);
	}
};
