// Warning: this file is generated by wrapper.py.

#pragma once

#include "transform.h"

#include "lua++.h"
#include "tools/string.h"

class PRS_Wrapper {
	static int NewPRS(lua_State* L) {
		return Lua::newObject<PRS>(L);
	}

	static int ToString(lua_State* L) {
		PRS* _p = Lua::callerPtr<PRS>(L);

		lua_pushstring(L, String::Format("PRS@0x%p", _p).c_str());
		return 1;
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<PRS>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewPRS", NewPRS });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deletePtr<PRS> },
			{ "__tostring", ToString }, 
			{ nullptr, nullptr }
		};

		Lua::initMetatable<PRS>(L, metalib, nullptr);
	}
};

class Transform_Wrapper {
	static int NewTransform(lua_State* L) {
		return Lua::fromIntrusive(L, new ITransform());
	}

	static int ToString(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);

		lua_pushstring(L, String::Format("Transform@0x%p", _p.get()).c_str());
		return 1;
	}

	// bool IsAttachedToScene()
	static int IsAttachedToScene(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->IsAttachedToScene());
	}

	// void AddChild(Transform child)
	static int AddChild(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		Transform child = Lua::get<Transform>(L, 2);
		
		_p->AddChild(child);
		return 0;
	}

	// void RemoveChild(Transform child)
	static int RemoveChild(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		Transform child = Lua::get<Transform>(L, 2);
		
		_p->RemoveChild(child);
		return 0;
	}

	// void RemoveChildAt(uint index)
	static int RemoveChildAt(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		uint index = Lua::get<uint>(L, 2);
		
		_p->RemoveChildAt(index);
		return 0;
	}

	// void SetParent(Transform value)
	static int SetParent(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		Transform value = Lua::get<Transform>(L, 2);
		
		_p->SetParent(value);
		return 0;
	}

	// Transform GetParent()
	static int GetParent(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetParent());
	}

	// glm::vec3 TransformPoint(const glm::vec3& point)
	static int TransformPoint(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 point = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->TransformPoint(point));
	}

	// glm::vec3 TransformDirection(const glm::vec3& direction)
	static int TransformDirection(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 direction = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->TransformDirection(direction));
	}

	// glm::vec3 InverseTransformPoint(const glm::vec3& point)
	static int InverseTransformPoint(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 point = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->InverseTransformPoint(point));
	}

	// glm::vec3 InverseTransformDirection(const glm::vec3& direction)
	static int InverseTransformDirection(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 direction = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->InverseTransformDirection(direction));
	}

	// Transform FindChild(const std::string& path)
	static int FindChild(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		std::string path = Lua::get<std::string>(L, 2);
		
		return Lua::push(L, _p->FindChild(path));
	}

	// int GetChildCount()
	static int GetChildCount(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetChildCount());
	}

	// Transform GetChildAt(int i)
	static int GetChildAt(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		int i = Lua::get<int>(L, 2);
		
		return Lua::push(L, _p->GetChildAt(i));
	}

	// Enumerable GetChildren()
	static int GetChildren(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		ITransform::Enumerable _r = _p->GetChildren();
		return Lua::pushList(L, std::vector<ITransform::Enumerable::value_type>(_r.begin(), _r.end()));
	}

	// void SetScale(const glm::vec3& value)
	static int SetScale(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetScale(value);
		return 0;
	}

	// void SetPosition(const glm::vec3& value)
	static int SetPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetPosition(value);
		return 0;
	}

	// void SetRotation(const glm::quat& value)
	static int SetRotation(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::quat value = Lua::get<glm::quat>(L, 2);
		
		_p->SetRotation(value);
		return 0;
	}

	// void SetEulerAngles(const glm::vec3& value)
	static int SetEulerAngles(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetEulerAngles(value);
		return 0;
	}

	// glm::vec3 GetScale()
	static int GetScale(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetScale());
	}

	// glm::vec3 GetPosition()
	static int GetPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetPosition());
	}

	// glm::quat GetRotation()
	static int GetRotation(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetRotation());
	}

	// glm::vec3 GetEulerAngles()
	static int GetEulerAngles(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetEulerAngles());
	}

	// void SetLocalScale(const glm::vec3& value)
	static int SetLocalScale(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetLocalScale(value);
		return 0;
	}

	// void SetLocalPosition(const glm::vec3& value)
	static int SetLocalPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetLocalPosition(value);
		return 0;
	}

	// void SetLocalRotation(const glm::quat& value)
	static int SetLocalRotation(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::quat value = Lua::get<glm::quat>(L, 2);
		
		_p->SetLocalRotation(value);
		return 0;
	}

	// void SetLocalEulerAngles(const glm::vec3& value)
	static int SetLocalEulerAngles(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 value = Lua::get<glm::vec3>(L, 2);
		
		_p->SetLocalEulerAngles(value);
		return 0;
	}

	// glm::vec3 GetLocalScale()
	static int GetLocalScale(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetLocalScale());
	}

	// glm::vec3 GetLocalPosition()
	static int GetLocalPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetLocalPosition());
	}

	// glm::quat GetLocalRotation()
	static int GetLocalRotation(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetLocalRotation());
	}

	// glm::vec3 GetLocalEulerAngles()
	static int GetLocalEulerAngles(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetLocalEulerAngles());
	}

	// glm::mat4 GetLocalToWorldMatrix()
	static int GetLocalToWorldMatrix(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetLocalToWorldMatrix());
	}

	// glm::mat4 GetWorldToLocalMatrix()
	static int GetWorldToLocalMatrix(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetWorldToLocalMatrix());
	}

	// glm::vec3 GetLocalToWorldPosition(const glm::vec3& position)
	static int GetLocalToWorldPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 position = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->GetLocalToWorldPosition(position));
	}

	// glm::vec3 GetWorldToLocalPosition(const glm::vec3& position)
	static int GetWorldToLocalPosition(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		glm::vec3 position = Lua::get<glm::vec3>(L, 2);
		
		return Lua::push(L, _p->GetWorldToLocalPosition(position));
	}

	// glm::vec3 GetUp()
	static int GetUp(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetUp());
	}

	// glm::vec3 GetRight()
	static int GetRight(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetRight());
	}

	// glm::vec3 GetForward()
	static int GetForward(lua_State* L) {
		Transform& _p = *Lua::callerIntrusivePtr<Transform>(L);
		return Lua::push(L, _p->GetForward());
	}

public:
	static void create(lua_State* L) {
		Lua::createMetatable<Transform>(L);
	}
	
	static void initialize(lua_State* L, std::vector<luaL_Reg>& funcs, std::vector<luaL_Reg>& fields) {
		funcs.push_back(luaL_Reg { "NewTransform", NewTransform });

		luaL_Reg metalib[] = {
			{ "__gc", Lua::deleteIntrusivePtr<Transform> },
			{ "__tostring", ToString }, 
			{ "IsAttachedToScene", IsAttachedToScene },
			{ "AddChild", AddChild },
			{ "RemoveChild", RemoveChild },
			{ "RemoveChildAt", RemoveChildAt },
			{ "SetParent", SetParent },
			{ "GetParent", GetParent },
			{ "TransformPoint", TransformPoint },
			{ "TransformDirection", TransformDirection },
			{ "InverseTransformPoint", InverseTransformPoint },
			{ "InverseTransformDirection", InverseTransformDirection },
			{ "FindChild", FindChild },
			{ "GetChildCount", GetChildCount },
			{ "GetChildAt", GetChildAt },
			{ "GetChildren", GetChildren },
			{ "SetScale", SetScale },
			{ "SetPosition", SetPosition },
			{ "SetRotation", SetRotation },
			{ "SetEulerAngles", SetEulerAngles },
			{ "GetScale", GetScale },
			{ "GetPosition", GetPosition },
			{ "GetRotation", GetRotation },
			{ "GetEulerAngles", GetEulerAngles },
			{ "SetLocalScale", SetLocalScale },
			{ "SetLocalPosition", SetLocalPosition },
			{ "SetLocalRotation", SetLocalRotation },
			{ "SetLocalEulerAngles", SetLocalEulerAngles },
			{ "GetLocalScale", GetLocalScale },
			{ "GetLocalPosition", GetLocalPosition },
			{ "GetLocalRotation", GetLocalRotation },
			{ "GetLocalEulerAngles", GetLocalEulerAngles },
			{ "GetLocalToWorldMatrix", GetLocalToWorldMatrix },
			{ "GetWorldToLocalMatrix", GetWorldToLocalMatrix },
			{ "GetLocalToWorldPosition", GetLocalToWorldPosition },
			{ "GetWorldToLocalPosition", GetWorldToLocalPosition },
			{ "GetUp", GetUp },
			{ "GetRight", GetRight },
			{ "GetForward", GetForward },
			{ nullptr, nullptr }
		};

		Lua::initMetatable<Transform>(L, metalib, TypeID<Component>::string());
	}
};
