import os;
import sys;

def Run(path, callback):
	fullname = os.path.basename(path);
	filename = fullname[:fullname.find(".")];

	inf = filename + ".txt";
	outf = filename + ".h";

	if (len(sys.argv) > 1): inf = sys.argv[1];
	if (len(sys.argv) > 2): outf = sys.argv[2];

	answer = "";

	while answer.lower() != "y" and answer.lower() != "n":
		answer = input("read from %s, write to %s, continue? (y/n)\n" % (inf, outf));

	if answer.lower() != "y": return;

	tinf = os.stat(inf).st_mtime;
	toutf = os.stat(outf).st_mtime;
	tself = os.stat(path).st_mtime;

	if tself <= toutf and tinf <= toutf:
		print("Nothing changed, skip.");
	else:
		dest = open(outf, "w");
		dest.write("// Warning: this file is generated by " + fullname + ".\n\n");

		try:
			callback(open(inf, "r"), dest);
		except Exception as e:
			print(e);
		else:
			print("Success.");

	input("Press enter to exit...");
